-- A simple trigger to find plyer and send it to controller to teleport

local e = require "game.events"

local msg_colision_response = hash("collision_response")
local player_group = hash("player")
local controller = "controller"

function on_message(self, message_id, message, sender)
	if message_id == msg_colision_response then
		if message.other_group == player_group then
			msg.post(controller, e.EVENTS.PORTAL_READY, { go_id = message.other_id })
		end
	end
end